version: '3.3'

services:
  backend-db:
    container_name: backend-database
    image: mysql/mysql-server:8.0
    volumes:
      - ./mysql-volume:/var/lib/mysql
    ports:
      - '3360:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MySQL_ALLOW_EMPTY_PASSWORD: yes
    networks:
      - springmysql-net
  backend-app:
    image: sleepypoem:ecommerce-backend-${PACKAGE_VERSION}
    build:
      context: ./back-end/ecommerce
      args:
        - PACKAGE_NAME=${PACKAGE_NAME}
        - PACKAGE_VERSION=${PACKAGE_VERSION}
    container_name: spring-app
    depends_on:
      - backend-db
    ports:
      - "8081:8081"
    networks:
      - springmysql-net
    environment:
      - MYSQL_HOST=backend-db
      - MYSQL_USERNAME=admin
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=ecommerce
      - MYSQL_PORT=3306
#      - LOCAL_HOST=host.docker.internal
#    links:
#      - keycloak
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
networks:
  springmysql-net:
